### ISSUE TITLE
question about data range

### ISSUE THREAD

**Issue by pierowu** [Lornatang/CycleGAN-PyTorch#9]
![image](https://user-images.githubusercontent.com/61963313/218260524-4a37ecd0-27c8-4f61-8ef7-897a23db0c8f.png)
The range of data from datasets is between [0,1]. 
While the range of data which is generated from generator is between [-1,1].
![image](https://user-images.githubusercontent.com/61963313/218260752-5d2e573d-b1c3-401a-a899-599c7ceeb2e0.png)

How can these two ranges compare with each other? Is there something wrong or I made some mitakes?  Can anyone help me?

![image](https://user-images.githubusercontent.com/61963313/218260721-64328f36-dbd6-45b9-bff2-a732be410250.png)

**Comment by Lornatang** [comment]
Thank you find my error, input data range should [-1, 1], and output data range should [-1, 1]
